### PR TITLE
Make config file option optional, and make its help text more informative

### PR DESCRIPTION
**Pull request by samwilson**
It wasn't possible to not pass the config file name (`-c`).

### CODE REVIEW

**Comment by TheFox** [comment]
For which command was is not possible to not set it? Beside `Auth` you always have to use a configuration file. Otherwise this command will not work.

**Comment by samwilson** [comment]
Sorry, I should have been clearer...

I thought it was meant to be that if no `-c` was provided (or no env var set) then it'd use `config.yml` in the current directory. This wasn't working for me, e.g.

```bash
$ ./bin/flickr-cli auth

In FlickrCliCommand.php line 241:
                              
  No config file path found.  

auth [-c|--config [CONFIG]] [-f|--force]
```

Which should either work, or the `-c` option should become mandatory.

I think! :) Sorry if I'm misunderstanding something.

**Comment by TheFox** [comment]
No, this is fine. I think it's my fault because the [Docker environment](https://github.com/TheFox/flickr-cli/blob/aaa94fe859ccd2db13dcf5d8cbac971244125e56/Dockerfile#L5) always has the `FLICKRCLI_CONFIG` environment variable set. I guess because of this I wrote the PHP like this. Inside Docker it's totally fine to always have the environment variable set, but then you have a problem on a non-Docker environment.

Let me check the details.

**Comment by TheFox** [comment]
Please be aware of running `composer update`. I fixed some things in 0a3006f285a1342aa6a7c0bde9682872c583d861 and 1ea7c69affe2b0cd9972f61400844a6ee3022e97.

**Pull request merged**
